name: Feature
description: New functionality
labels: [enhancement]
body:
  - type: textarea
    id: what
    attributes:
      label: What
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
  - type: textarea
    id: approach
    attributes:
      label: Possible approach
